### ISSUE TITLE
Wishlist: blod- og andre laboratorieprøver

### ISSUE THREAD

**Issue by zerodogg** [olejon/mdapp#1]
Det hadde vore nyttig om ein kunne sjå referanseverdiar på diverse laboratorieprøvar, som på http://analyseoversikten.no/ 

Om det ikkje finst nokon datakjelde som kan nyttast, kanskje analyseoversikten kunne visast på same måte som legevakthandboka?

**Comment by olejon** [comment]
Skal føre det opp på to-do-lista :-)

**Comment by olejon** [comment]
Er det forskjell på å søke på analyseoversikten.no og http://brukerhandboken.no/ ang. referanseverdier o.l.?

**Comment by olejon** [comment]
analyseoversikten.no har en fin mobiltilpasset nettside, så skal legge den til under oppslagsverk i sidemenyen, sammen med brukerhåndboken.

**Comment by zerodogg** [comment]
Trur ikkje det er særlig forskjell. Visstnok skal forskjellege laboratorier ha nokre små variasjonar i enkelte referanseverdiar (gr. utstyret og metodane som vart nytta), men i dei spesielle tilfellene vil jo det vere nokon som får «feil» uansett (og då er dei vel òg klar over det sjølv), så som referansekjelde trur eg det er mykje det same. Brukarhandboka er kanskje litt meir generell enn analyseoversikten (som er HUS sin), og skriv jo ting som «Analytisk variasjon er metodeavhengig og vil kunne variere ulike laboratorier imellom.»?

**Comment by zerodogg** [comment]
Vakkert :)

**Comment by olejon** [comment]
Fint. Brukerhåndboken får du allerede treff i dersom du søker på norsk i seksjonen Sykdommer og behandlinger, f.eks. på Glukose. For å rask skrolle ned til resultatene, trykk på "Skroll til" og velg Nasjonal brukerhåndbok i medisinsk biokjemi.

**Comment by olejon** [comment]
Anaylyseoversikten er nå lagt til under Oppslagsverk i sidemenyen. Du som tester vil få oppdateringen innen noen timer.
