### ISSUE TITLE
Wishlist: referansemateriell

### ISSUE THREAD

**Issue by zerodogg** [olejon/mdapp#2]
Det hadde vore nyttig å hatt rask tilgang i appen til ymse referansemateriell. Då tenkjer eg ting som glasgow coma scale og VAS (kanskje òg ESAS-r o.l., men det er strengt tatt litt mindre nyttig).

GCS og VAS er særleg ting som er nyttig å ha «i lomma» i klinisk praksis. Kanskje meir for sjukepleiarar enn lækjarar, men kan då evt. leggjast til ein «gøym sjukepleieverkty» el.likn. i innstillingane?

**Comment by olejon** [comment]
Du kan rimelig kjapt finne GCS og VAS ved å søke på engelsk (eller norsk for den del) i seksjonen Sykdommer og behandlinger.

Screenshots:
https://dl.dropboxusercontent.com/u/8593574/Diverse/GCS.png
https://dl.dropboxusercontent.com/u/8593574/Diverse/VAS.png

Her har eg søkt etter henholdsvis "Glasgow Coma Scale" og "VAS Scale" på engelsk og trykt på første treff i UpToDate og bladd litt nedover. Dei fleste kildene i Seksjonen Sykdommer og behandlinger vil gi treff på disse søketermene på både engelsk og norsk.

**Comment by zerodogg** [comment]
Det er eg klar over, men det hadde vore nyttig å ha dei lett tilgjengeleg - utan å måtte gå via søkjefunksjonen. Mange pleiarar går rundt med laminerte GCS o.l. i lomma - personleg har eg meir enn nok der allereie (det er relativt utruleg kor mykje rart som finn vegen der i laupet av ei vakt), og å ha hatt dei to-tre trykk unna på mobilen ville stort sett gjere same nytten. Både GCS og VAS kan òg finnast med eit kjapt søk i ein vanleg nettlesar, tanken er å ha dei lett tilgjengeleg for å kjapt ha som referanse - digital erstatning av det laminerte papiret.

**Comment by olejon** [comment]
Skjønner. En Skalaer-seksjon i sidemenyen hadde ikke vært dumt, og en smal sak å implementere. Må bare finne bilder uten opphavsrett. Kom gjerne med flere forslag.

**Comment by olejon** [comment]
Kan du legge ved bilder av disse laminerte papirene du går rundt med så jeg kan finne dem?

**Comment by zerodogg** [comment]
Eg har dei ikkje (kunne hatt bruk for dei, men då gjerne på mobilen :) ).

Typisk er det for GCS eit ark a'la den til høgre her: https://dpbfm6h358sh7.cloudfront.net/images/370046/188581469.jpg eller denne: http://www.firstaidforfree.com/wp-content/uploads/2013/11/GCS.jpg - altså berre ein enkel referanse som ein kan ta eit kjapt blikk på medan ein er ved senga til ein pasient for så å rekne ut skår.

For VAS tenkjer eg noko a'la nr. to her vil vere http://tidsskriftet.no/image/2014/T-13-1145-01-Sps.jpg (kjelde: http://tidsskriftet.no/article/3136652). Å hatt denne lett tilgjengeleg vil vere spesielt nyttig sidan mange tenderer til å berre nytte ein verbal numerisk skala i staden for «ekte» VAS (som overnemnte artikkel òg tek føre seg).

Ein annan som kan vere nyttig kan vere MEWS, som siste halvdel av http://www.ihi.org/resources/PublishingImages/Image_PatientAssessmentObservationInfusionMonitoring.jpg (frå http://www.ihi.org/resources/Pages/ImprovementStories/EarlyWarningSystemsScorecardsThatSaveLives.aspx)

Andre som er vanleg i bruk, men som eg er uviss på om vil vere nyttig i appen er t.d. NRS 2002 - Screening av ernæringsmessig risiko: http://demo.datakvalitet.no/egg/dok/dok35812.pdf - Denne er nytta rutinemessig kvartfall ved HUS, men er kanskje litt stor og uhandterbar til å appifisere (og er ikkje noko som det vil vere noko problem å gå på vaktrommet og hente). Elles òg ESAS-r - http://www.unn.no/getfile.php/UNN%20INTER/Enhet/K3K_web/Lindrende/ESAS_r_NORWEGIAN_version_final1_180112%281%29.pdf - men igjen relativt uhamseleg, og kan nok fint hentast på vaktrommet.

**Comment by olejon** [comment]
Flere av disse krever utfylling av data, så da må de vel "appifiseres" som du sier. I første omgang kan jeg se på å implementere de som ikke krever utfylling av data. Forstår jeg det rett av dere bare har med dere bilder/ark (ikke fyller ut data på selve bildet/arket) på GCS, VAS og MEWS?

**Comment by zerodogg** [comment]
VAS er i stor grad «peik på der du ligger». GCS er jo ein numerisk skår som ein berre reknar ut og så kan loggføre sjølve skåren, eller evt. setje i gang tiltak på bakgrunn av. Den kan jo gjerast interaktiv, men fungerer òg fint som ein referanse a'la den eg lenkja til. Ingen av desse har noko ark el. likn. som vart fylt ut. MEWS kan òg fint nyttast utan å fylle noko ut, sidan det igjen er ein relativt simpel skår. Sistnemnte er nytta til overvaking av kritisk sjuke, og t.d. i tidleg postoperativ overvaking, og gir ein indikasjon på om pas. tilstand vart eller er i ferd med å forverre seg.

**Comment by olejon** [comment]
Takk. Skal se på implementering av disse i nærmeste fremtid.

Det beste hadde vært å hatt nøyaktig de laminerte bildene sykepleiere går rundt med, for å gjøre "overgangen" sømløs. Har du mulighet til å få tak i dem i digitalt format, helst i høy kvalitet? Kan evt. skannes.

**Comment by zerodogg** [comment]
Eg skal gjere eit forsøk, men vil nok ta litt tid

**Comment by olejon** [comment]
Supert, den er god :-)

**Comment by olejon** [comment]
Ny versjon ute for testere innen et par timer med ny seksjon i sidemenyen kalt Skalaer. Så langt er VAS, GCS og MEWS med. Tilbakemeldinger er velkomne. Håper fortsatt på å få de bildene som brukes på norske sykehus.

**Comment by zerodogg** [comment]
Den er veldig fin, og nyttig :+1: 

Eg skal prøve å få tak i dei, men vil som sagt ta ei stund, for eg har ikkje kontakt med nokon av dei som hadde pr. no.

**Comment by olejon** [comment]
Har forhørt meg med en annen sykepleiestudent, som sa:

> I følge den ene sykepleieren er det ofte legemiddelprodusentene som deler ut VAS-skalaen. Sykepleieren mente at de skalaene du har funnet fungere bra, og ligner på de som brukes.

Hun skulle forhøre seg med en 2. års medisinstudent som utenom studiene jobber på Haukeland.

**Comment by zerodogg** [comment]
GCS referanse:
![gcs](https://cloud.githubusercontent.com/assets/60426/7592792/cb552078-f8d5-11e4-9d19-8d6eb2414610.jpg)

Ymse anna eg fann samstundes (mindre nyttig, men tok med likevel).
![kommunikasjon](https://cloud.githubusercontent.com/assets/60426/7592791/cb52e4f2-f8d5-11e4-90c4-ded9210b262b.jpg)

**Comment by zerodogg** [comment]
Fant i farge
![huskeliste](https://cloud.githubusercontent.com/assets/60426/7592851/2eb772f6-f8d6-11e4-9aa9-21c20257c384.jpg)

**Comment by olejon** [comment]
Flott :-) Er mulig å få de skannet i bedre kvalitet? Dvs mindre hvite kanter rundt, og spesielt ABCDE og ISBAR i brukbar kvalitet? Helst digitalt då, men skanning i høg oppløsning går fint det også.

**Comment by zerodogg** [comment]
Tviler på at eg får gjort det med det fyrste. Eksamensperiode no :p

Uansett, her er bilete av ein av VAS-skalaene nokon hadde.
![img_20150514_093549](https://cloud.githubusercontent.com/assets/60426/7649496/d8359cd6-faed-11e4-9893-44b8dd13e2bd.jpg)
![img_20150514_093543](https://cloud.githubusercontent.com/assets/60426/7649497/d8388db0-faed-11e4-88f3-087931fbf2f5.jpg)

**Comment by olejon** [comment]
Ok, da lar jeg de gjeldende skalaene være enn så lenge. Takk :-)
