### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [olejon/mdapp#7]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

Sequence 1:

1. Scroll Down the a list on the main activity
2. Orientation Change

Sequence 2:

1. Open Side Drawer
2. Scroll Down
3. Orientation Change

Sequence 3-9:

1. Open Side Drawer
2. Click on:
a. Innstillinger
b. Legevakthandboken
c. ICD-10
d. Legemiddelfirmaer
e. Apotek
f. Skalaer
g. Varsler
3. Scroll Down
4. Orientation Change

**Comment by olejon** [comment]
This app is for Norwegian health care workers only. The issues can be reproduced, yes. Android should in theory handle such things. May be a bug in the new Android 25 API and build tools, which there are updates for now which can be used in the next version. Will keep it in mind. But in general if you can not report issues in Norwegian, please do not, as you are probably not a user of this app then. Correct me if I am wrong.
