### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [olejon/mdapp#8]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Open Side Drawer
2. Click on Kalkulatorer
3. Enter BMI data
4. Click on Beregn
5. Orientation Change

Sequence 2:
1. Open Side Drawer
2. Click on Kalkulatorer
3. Enter Midjemal data
4. Click on Beregn
5. Orientation Change

Sequence 3:
1. Open Side Drawer
2. Click on Kalkulatorer
3. Enter Korrigert QT-tid data
4. Click on Beregn
5. Orientation Change

Sequence 4:
1. Open Side Drawer
2. Click on Kalkulatorer
3. Click on info icon
4. Orientation Change

**Comment by olejon** [comment]
This app is for Norwegian health care workers only. The issues can be reproduced, yes. Android should in theory handle such things. May be a bug in the new Android 25 API and build tools, which there are updates for now which can be used in the next version. Will keep it in mind. But in general if you can not report issues in Norwegian, please do not, as you are probably not a user of this app then. Correct me if I am wrong.
